apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-ubuntu-slave
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-ubuntu-slave
  template:
    metadata:
      labels:
        app: jenkins-ubuntu-slave
    spec:
      serviceAccountName: jenkins-slave
      containers:
      - name: jenkins-ubuntu-slave
        image: ahmadesmailshata/enhanced-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock